Repository bioinf-internship-2020-team-varcall/bioinf-practice-2020-variant-caller, pull requests merged in 2020-05, with the labels that each got.

#34 Filtering reads
  Design/Filtering_reads.md
Labels: design, enhancement

#38 Now intervals are static
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/IntervalsHandler.java
  VariantCaller/src/test/java/IntervalsHandlerTest.java
Labels: enhancement

#39 FastaHandler holds indexed file
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/fasta/FastaHandlerUnableToFindEntryException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/fasta/FastaMultipleSequencesException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/FastaHandler.java
  VariantCaller/src/test/java/FastaHandlerTest.java
  VariantCaller/src/test/resources/test1.fasta
  VariantCaller/src/test/resources/test3.fasta
Labels: enhancement

#37 Merging overlapping intervals
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/IntervalsHandler.java
  VariantCaller/src/test/java/IntervalsHandlerTest.java
  VariantCaller/src/test/resources/test4_overlapping.bed
Labels: enhancement

#35 Searching variants
  Design/Search_variants.md
Labels: design, enhancement

#36 Filtering reads
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/sam/SamNoRelatedReadsException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/SamHandler.java
  VariantCaller/src/test/java/SamHandlerTest.java
  VariantCaller/src/test/resources/test1.bed
  VariantCaller/src/test/resources/test2.sam
Labels: implementation

#40 Вывод VCF
  Design/VCF_output.md
Labels: design
