Repository bioinf-internship-2020-team-varcall/bioinf-practice-2020-variant-caller, pull requests merged in 2020-03, with the labels that each got.

#10 Integration test design
  Design/Integration_test.md
Labels: documentation

#18 Added Design/Read_fasta_reference.md
  Design/Read_fasta_reference.md
Labels: documentation

#17 CI design
  Design/ci_design.md
Labels: documentation

#19 CI implementation
  .github/workflows/project_testing.yml
  Docs/ci.md
Labels: implementation

#24 LFS support for CI
  .github/workflows/project_testing.yml
Labels: hotfix

#25 Fixes makeConcatWithConstants missing #21
  VariantCaller/build.gradle
  VariantCaller/config/spotbugs/spotbugs.xml
Labels: hotfix

#22 Design Sam File Handler
  Design/Sam_File_Handler.md
Labels: design

#23 Intervals Handler
  Design/Read_intervals.md
Labels: design
