Repository bioinf-internship-2020-team-varcall/bioinf-practice-2020-variant-caller, pull requests merged in 2020-04, with the labels that each got.

#20 Reading fasta reference
  VariantCaller/build.gradle
  VariantCaller/src/integrationTest/java/CommandLineArgsrIntegTest.java
  VariantCaller/src/integrationTest/resources/test1.bed
  VariantCaller/src/integrationTest/resources/test1.fasta
  VariantCaller/src/integrationTest/resources/test1.sam
  VariantCaller/src/integrationTest/resources/test2.bed
  VariantCaller/src/integrationTest/resources/test2.fasta
  VariantCaller/src/integrationTest/resources/test2.sam
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/cmdline/CommandLineParser.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/cmdline/ParsedArguments.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/FastaHandler.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/TestHelper.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/exceptions/messages/CommandLineParserMessages.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/exceptions/messages/FastaHandlerMessages.java
  VariantCaller/src/test/java/CommandLineParserTest.java
  VariantCaller/src/test/java/FastaHandlerTest.java
  VariantCaller/src/test/java/ParsedArgumentsTest.java
  VariantCaller/src/test/resources/test1.bed
  VariantCaller/src/test/resources/test1.fasta
  VariantCaller/src/test/resources/test1.fna
  VariantCaller/src/test/resources/test2.bed
  VariantCaller/src/test/resources/test2.fasta
  VariantCaller/src/test/resources/test3.fasta
Labels: enhancement, implementation, team approve

#29 Pull request template
  .github/pull_request_template.md
Labels: implementation

#30 Adding dependencies for SpotBugs annotations
  VariantCaller/build.gradle
Labels: enhancement

#26 Reading SAM
  VariantCaller/src/integrationTest/resources/test1.fasta
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/Main.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/SamHandler.java
  VariantCaller/src/test/java/SamHandlerTest.java
Labels: implementation, team approve

#28 Reading intervals
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/cmdline/CommandLineParser.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/cmdline/ParsedArguments.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/IntervalsHandler.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/exceptions/messages/CommandLineParserMessages.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/exceptions/messages/IntervalsHandlerMessages.java
  VariantCaller/src/test/java/CommandLineParserTest.java
  VariantCaller/src/test/java/IntervalsHandlerTest.java
  VariantCaller/src/test/java/ParsedArgumentsTest.java
  VariantCaller/src/test/resources/test1.bed
  VariantCaller/src/test/resources/test2.bed
  VariantCaller/src/test/resources/test3_malformed.bed
Labels: implementation, team approve

#33 Exceptions hieararchy v1.0.0
  VariantCaller/src/integrationTest/java/CommandLineArgsrIntegTest.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/cmdline/CommandLineParser.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/cmdline/ParsedArguments.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/HandlerException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/ParserException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/FastaHandlerException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/RegionHandlerException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/SamHandlerException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/fasta/FastaMultipleSequencesException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/region/RegionIllegalEndException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/region/RegionIllegalIntervalException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/region/RegionIllegalStartException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/handlers/region/RegionReadingException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/FastaParserException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/RegionParserException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/SamParserException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/fasta/FastaArgsSizeException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/fasta/FastaInvalidExtensionException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/fasta/FastaPathNotExistsException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/region/RegionBothIntervalOptionsException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/region/RegionInvalidException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/region/RegionInvalidExtensionException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/region/RegionPathNotExistsException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/sam/SamArgsSizeException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/sam/SamInvalidExtensionException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/exceptions/parser/sam/SamPathNotExistsException.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/FastaHandler.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/IntervalsHandler.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/handlers/SamHandler.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/exceptions/messages/CommandLineParserMessages.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/exceptions/messages/FastaHandlerMessages.java
  VariantCaller/src/main/java/com/epam/bioinf/variantcaller/helpers/exceptions/messages/IntervalsHandlerMessages.java
  VariantCaller/src/test/java/CommandLineParserTest.java
  VariantCaller/src/test/java/FastaHandlerTest.java
  VariantCaller/src/test/java/IntervalsHandlerTest.java
  VariantCaller/src/test/java/ParsedArgumentsTest.java
Labels: team approve
